version: '3.8'
services:
  ledger-service:
    build:
      context: .
      dockerfile: ledger-service/Dockerfile
    ports:
      - "8081:8081"
    networks:
      - fintech-net

  transfer-service:
    build:
      context: .
      dockerfile: transfer-service/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - LEDGER_SERVICE_BASE_URL=http://ledger-service:8081
    networks:
      - fintech-net
    depends_on:
      - ledger-service

networks:
  fintech-net:
    driver: bridge
